#ifndef DEVDRIV_2A
#define DEVDRIV_2A

#include <unistd.h>
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <sensehat.h>
#include <signal.h>
#include <stdlib.h>

#define RED 32768
#define GREEN 256
#define BLUE 255
#define OFF 0

#define MATRIXAXISSIZE 8

uint16_t ArrowUp[MATRIXAXISSIZE][MATRIXAXISSIZE] = {
    {OFF, OFF, OFF, BLUE, BLUE, OFF, OFF, OFF},
    {OFF, OFF, BLUE, BLUE, BLUE, BLUE, OFF, OFF},
    {OFF, BLUE, OFF, BLUE, BLUE, OFF, BLUE, OFF},
    {BLUE, OFF, OFF, BLUE, BLUE, OFF, OFF, BLUE},
    {OFF, OFF, OFF, BLUE, BLUE, OFF, OFF, OFF},
    {OFF, OFF, OFF, BLUE, BLUE, OFF, OFF, OFF},
    {OFF, OFF, OFF, BLUE, BLUE, OFF, OFF, OFF},
    {OFF, OFF, OFF, BLUE, BLUE, OFF, OFF, OFF}};

uint16_t ArrowDown[MATRIXAXISSIZE][MATRIXAXISSIZE] = {
    {OFF, OFF, OFF, BLUE, BLUE, OFF, OFF, OFF},
    {OFF, OFF, OFF, BLUE, BLUE, OFF, OFF, OFF},
    {OFF, OFF, OFF, BLUE, BLUE, OFF, OFF, OFF},
    {OFF, OFF, OFF, BLUE, BLUE, OFF, OFF, OFF},
    {BLUE, OFF, OFF, BLUE, BLUE, OFF, OFF, BLUE},
    {OFF, BLUE, OFF, BLUE, BLUE, OFF, BLUE, OFF},
    {OFF, OFF, BLUE, BLUE, BLUE, BLUE, OFF, OFF},
    {OFF, OFF, OFF, BLUE, BLUE, OFF, OFF, OFF}};

uint16_t ArrowLeft[MATRIXAXISSIZE][MATRIXAXISSIZE] = {
    {OFF, OFF, OFF, GREEN, OFF, OFF, OFF, OFF},
    {OFF, OFF, GREEN, OFF, OFF, OFF, OFF, OFF},
    {OFF, GREEN, OFF, OFF, OFF, OFF, OFF, OFF},
    {GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN},
    {GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN},
    {OFF, GREEN, OFF, OFF, OFF, OFF, OFF, OFF},
    {OFF, OFF, GREEN, OFF, OFF, OFF, OFF, OFF},
    {OFF, OFF, OFF, GREEN, OFF, OFF, OFF, OFF}};

uint16_t ArrowRight[MATRIXAXISSIZE][MATRIXAXISSIZE] = {
    {OFF, OFF, OFF, OFF, GREEN, OFF, OFF, OFF},
    {OFF, OFF, OFF, OFF, OFF, GREEN, OFF, OFF},
    {OFF, OFF, OFF, OFF, OFF, OFF, GREEN, OFF},
    {GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN},
    {GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN},
    {OFF, OFF, OFF, OFF, OFF, OFF, GREEN, OFF},
    {OFF, OFF, OFF, OFF, OFF, GREEN, OFF, OFF},
    {OFF, OFF, OFF, OFF, GREEN, OFF, OFF, OFF}}; 

uint16_t Crosshair[MATRIXAXISSIZE][MATRIXAXISSIZE] = {
    {OFF, RED, RED, RED, RED, RED, RED, OFF},
    {RED, OFF, OFF, OFF, OFF, OFF, OFF, RED},
    {RED, OFF, OFF, OFF, OFF, OFF, OFF, RED},
    {RED, OFF, OFF, RED, RED, OFF, OFF, RED},
    {RED, OFF, OFF, RED, RED, OFF, OFF, RED},
    {RED, OFF, OFF, OFF, OFF, OFF, OFF, RED},
    {RED, OFF, OFF, OFF, OFF, OFF, OFF, RED},
    {OFF, RED, RED, RED, RED, RED, RED, OFF}}; 
    
uint16_t Off[MATRIXAXISSIZE][MATRIXAXISSIZE] = {
    {OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF},
    {OFF, OFF, OFF, OFF, OFF, OFF, OFF, OFF}}; 

void sighandler(int signum);

void SetJoystickDirection(unsigned char dir);

#endif